import { create } from "zustand";
import { persist, createJSONStorage } from 'zustand/middleware'
import { createBrowserClient } from '@supabase/ssr';
import { toast } from 'sonner';

export interface Notification {
  id: string;
  title: string;
  message: string;
  read: boolean;
  createdAt: Date;
  userId?: string;
}

export interface NotificationStore {
  notifications: Notification[];
  fetchNotifications: () => Promise<void>;
  addNotification: (notification: Omit<Notification, 'id' | 'createdAt' | 'read'>) => void;
  markAsRead: (id: string) => Promise<void>;
  markAllAsRead: () => Promise<void>;
}

const supabase = createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);

export const useNotificationStore = create<NotificationStore>()(
  persist(
    (set, get) => ({
      notifications: [],
      
      fetchNotifications: async () => {
        const { data: { user } } = await supabase.auth.getUser();
        if (!user) return;
        
        try {
          const { data, error } = await supabase
            .from('notifications')
            .select('*')
            .eq('user_id', user.id)
            .order('created_at', { ascending: false });
          
          if (error) throw error;
          
          set({ 
            notifications: data.map(n => ({
              ...n,
              createdAt: new Date(n.created_at)
            })) 
          });
        } catch (error) {
          console.error("Error fetching notifications:", error);
          toast.error("Failed to load notifications.");
        }
      },

      addNotification: async (notification) => {
        const { data: { user } } = await supabase.auth.getUser();
        if (!user) {
          toast.error("You must be logged in to add a notification.");
          return;
        }

        const newNotification = {
          ...notification,
          id: '', // This will be generated by the DB
          user_id: user.id,
          read: false,
          created_at: new Date().toISOString(),
        };

        try {
          const { data, error } = await supabase
            .from('notifications')
            .insert(newNotification)
            .select()
            .single();

          if (error) throw error;

          set((state) => ({
            notifications: [{ ...data, createdAt: new Date(data.created_at) }, ...state.notifications],
          }));
          toast.success("Notification added!");
        } catch (error) {
          console.error("Error adding notification:", error);
          toast.error("Failed to add notification.");
        }
      },

      markAsRead: async (id: string) => {
        set((state) => ({
          notifications: state.notifications.map((n) =>
            n.id === id ? { ...n, read: true } : n
          ),
        }));
        
        try {
          const { error } = await supabase
            .from('notifications')
            .update({ read: true })
            .eq('id', id);
          
          if (error) throw error;
        } catch (error) {
          console.error("Error marking notification as read:", error);
          toast.error("Failed to update notification.");
          // Revert state if DB update fails
          set((state) => ({
            notifications: state.notifications.map((n) =>
              n.id === id ? { ...n, read: false } : n
            ),
          }));
        }
      },

      markAllAsRead: async () => {
        const originalNotifications = get().notifications;
        set((state) => ({
          notifications: state.notifications.map((n) => ({ ...n, read: true })),
        }));
        
        try {
          const { data: { user } } = await supabase.auth.getUser();
          if (!user) return;

          const { error } = await supabase
            .from('notifications')
            .update({ read: true })
            .eq('user_id', user.id)
            .eq('read', false);
          
          if (error) throw error;
        } catch (error) {
          console.error("Error marking all notifications as read:", error);
          toast.error("Failed to update notifications.");
          set({ notifications: originalNotifications }); // Revert on failure
        }
      },
    }),
    {
      name: 'notification-storage',
      storage: createJSONStorage(() => sessionStorage),
    }
  )
);